/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.main;

import commons.helpers.GenericHelper;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import static java.rmi.server.LogStream.log;
import javax.imageio.ImageIO;
import views.instructor.InstructorManager;
import views.schedule.LessonSchedule;
import views.utilities.MaintenanceMenu;
import views.program.ProgramManager;
import views.utilities.ReportsManager;
import views.student.StudentManager;
import static commons.helpers.NavHelper.setStudentType;
import static commons.helpers.NavHelper.addToNavHistory;
import static commons.helpers.NavHelper.clearNavHistory;

/**
 *
 * @author daynehammes
 */
public class MainMenu extends javax.swing.JFrame {

    private StudentManager studentManager = null;
    private InstructorManager instructorManager = null;
    private ProgramManager programManager = null;
    private ReportsManager reportsManager = null;
    private MaintenanceMenu maintenanceMenu = null;
    private LessonSchedule lessonSchedule = null;

    /**
     * Creates new form Menu
     */
    public MainMenu() {
        initComponents();
        // Set Window Icon
        try {
            BufferedImage favicon = ImageIO.read(getClass().getResource("/resources/icon16.png"));
            setIconImage(favicon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        setTitle("Dance Studios - Management System");
        setLocationRelativeTo(null);
        
            // Clear nav history
            clearNavHistory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        footerText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        studentsBtn = new javax.swing.JButton();
        newStudentsBtn = new javax.swing.JButton();
        instructorsBtn = new javax.swing.JButton();
        programsBtn = new javax.swing.JButton();
        unenrolledStudentBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        reportsBtn = new javax.swing.JButton();
        scheduleBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        maintenanceBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/banner-slim.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("The Best Place to Learn to Dance");

        footerText.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        footerText.setForeground(new java.awt.Color(102, 102, 102));
        footerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        footerText.setText("Developed by The Startup Coders, LLC");
        footerText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                footerTextMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Personnel Management"));

        studentsBtn.setText("Students");
        studentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsBtnActionPerformed(evt);
            }
        });

        newStudentsBtn.setText("New Students");
        newStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentsBtnActionPerformed(evt);
            }
        });

        instructorsBtn.setText("Instructors");
        instructorsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorsBtnActionPerformed(evt);
            }
        });

        programsBtn.setText("Programs");
        programsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programsBtnActionPerformed(evt);
            }
        });

        unenrolledStudentBtn.setText("Unenrolled Students");
        unenrolledStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unenrolledStudentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unenrolledStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newStudentsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(instructorsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(programsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(studentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newStudentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(unenrolledStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(instructorsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(programsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Settings Management"));

        reportsBtn.setText("Reports");
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });

        scheduleBtn.setText("Schedule");
        scheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.setToolTipText("");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        maintenanceBtn.setText("Utilities");
        maintenanceBtn.setToolTipText("");
        maintenanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maintenanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(scheduleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maintenanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(footerText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel2)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(footerText)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsBtnActionPerformed


        // Open Student Manager
        this.setEnabled(false);
        Thread thr = new Thread() {
            public void run() {

                // Reset current studentRow and studentFilter
                GenericHelper.studentRow = 0;
                GenericHelper.studentFilter = 0;

                setStudentType("Student");

                studentManager = new StudentManager();
                studentManager.setVisible(true);
                MainMenu.this.dispose();
            }
        };
        thr.start();
    }//GEN-LAST:event_studentsBtnActionPerformed

    private void newStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentsBtnActionPerformed


// Open New Student Manager
        this.setEnabled(false);
        Thread thr = new Thread() {
            public void run() {

                // Reset current studentRow and studentFilter
                GenericHelper.studentRow = 0;
                GenericHelper.studentFilter = 0;

                setStudentType("New Student");

                studentManager = new StudentManager();
                studentManager.setVisible(true);
                MainMenu.this.dispose();
            }
        };
        thr.start();

    }//GEN-LAST:event_newStudentsBtnActionPerformed

    private void instructorsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorsBtnActionPerformed
        // Open Instructor Manager
        this.setEnabled(false);
        Thread thr = new Thread() {
            public void run() {

                instructorManager = new InstructorManager();
                instructorManager.setVisible(true);
                MainMenu.this.dispose();
            }
        };
        thr.start();
    }//GEN-LAST:event_instructorsBtnActionPerformed

    private void programsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programsBtnActionPerformed
        // Open Program Manager
        this.setEnabled(false);
        Thread thr = new Thread() {
            public void run() {

                programManager = new ProgramManager();
                programManager.setVisible(true);
                MainMenu.this.dispose();
            }
        };
        thr.start();

    }//GEN-LAST:event_programsBtnActionPerformed

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        // Open Reports Manager
        this.setEnabled(false);
        Thread thr = new Thread() {
            public void run() {

                reportsManager = new ReportsManager();
                reportsManager.setVisible(true);
                MainMenu.this.dispose();
            }
        };
        thr.start();
    }//GEN-LAST:event_reportsBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // Exit Program
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void maintenanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceBtnActionPerformed
        // Open Maintenance Manager
        this.setEnabled(false);
        Thread thr = new Thread() {
            public void run() {

                maintenanceMenu = new MaintenanceMenu();
                maintenanceMenu.setVisible(true);
                MainMenu.this.dispose();
            }
        };
        thr.start();

    }//GEN-LAST:event_maintenanceBtnActionPerformed

    private void scheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleBtnActionPerformed

        // Open Lesson Schedule
        this.setEnabled(false);
        Thread thr = new Thread() {
            public void run() {

                lessonSchedule = new LessonSchedule();
                lessonSchedule.setVisible(true);
                MainMenu.this.dispose();
            }
        };
        thr.start();

    }//GEN-LAST:event_scheduleBtnActionPerformed

    private void footerTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerTextMouseClicked
        // open support email
        try {
            URI uri = new URI("http://www.google.com");
            Desktop.getDesktop().browse(uri);
        } catch (URISyntaxException ex) {
            log("URL is malformed. Cannot open browser.");
        } catch (IOException ex) {
            log("Cannot open browser.");
        }
    }//GEN-LAST:event_footerTextMouseClicked

    private void unenrolledStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unenrolledStudentBtnActionPerformed


        // Open New Student Manager
        this.setEnabled(false);
        Thread thr = new Thread() {
            public void run() {

                // Reset current studentRow and studentFilter
                GenericHelper.studentRow = 0;
                GenericHelper.studentFilter = 0;

                setStudentType("Unenrolled Student");

                studentManager = new StudentManager();
                studentManager.setVisible(true);
                MainMenu.this.dispose();
            }
        };
        thr.start();
    }//GEN-LAST:event_unenrolledStudentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel footerText;
    private javax.swing.JButton instructorsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton maintenanceBtn;
    private javax.swing.JButton newStudentsBtn;
    private javax.swing.JButton programsBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JButton scheduleBtn;
    private javax.swing.JButton studentsBtn;
    private javax.swing.JButton unenrolledStudentBtn;
    // End of variables declaration//GEN-END:variables
}
