/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.utilities;

import static commons.helpers.NavHelper.addToNavHistory;
import views.main.MainMenu;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author daynehammes
 */
public class MaintenanceMenu extends javax.swing.JFrame {

    private BackupRestoreManager backupRestoreManager = null;

    /**
     * Creates new form Menu
     */
    public MaintenanceMenu() {
        initComponents();
        // Set Window Icon
        try {
            BufferedImage favicon = ImageIO.read(getClass().getResource("/resources/icon16.png"));
            setIconImage(favicon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        setTitle("Dance Studios - Management System");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backupRestoreManagerBtn = new javax.swing.JButton();
        transactionManagerBtn = new javax.swing.JButton();
        mainLogo = new javax.swing.JLabel();
        mainTitleLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(541, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backupRestoreManagerBtn.setText("Backup/Restore Database");
        backupRestoreManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupRestoreManagerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backupRestoreManagerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 236, 40));

        transactionManagerBtn.setText("Run Custom SQL");
        transactionManagerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionManagerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(transactionManagerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 236, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 340, 150));

        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/banner-slim.png"))); // NOI18N
        getContentPane().add(mainLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 360, 90));

        mainTitleLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        mainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleLabel.setText("Maintenance Menu");
        getContentPane().add(mainTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 93, 200, 30));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backupRestoreManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupRestoreManagerBtnActionPerformed
        
        // Add current view to nav history
        addToNavHistory("MaintenanceMenu");
        
        // Open Backup/Restore Manager
        this.setEnabled(false);
        Thread thr = new Thread() {
            public void run() {

                backupRestoreManager = new BackupRestoreManager();
                backupRestoreManager.setVisible(true);
                MaintenanceMenu.this.dispose();
            }
        };
        thr.start();

    }//GEN-LAST:event_backupRestoreManagerBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MainMenu main_menu = new MainMenu();
        main_menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void transactionManagerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionManagerBtnActionPerformed

        // Add current view to nav history
        addToNavHistory("MaintenanceMenu");
        
        CustomSQLManager customSQLManager = new CustomSQLManager();
        customSQLManager.setVisible(true);
        MaintenanceMenu.this.dispose();


    }//GEN-LAST:event_transactionManagerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaintenanceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaintenanceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaintenanceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaintenanceMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaintenanceMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backupRestoreManagerBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JButton transactionManagerBtn;
    // End of variables declaration//GEN-END:variables
}
